#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status
set -e

# where we'll store files
OUTPUT_DIR="/tmp/s3-bashscripts"

# remove the output folder if it exists
rm -rf $OUTPUT_DIR

# lets create ouput folder
mkdir -p $OUTPUT_DIR

# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # generate a random file name
    FILE_NAME="$OUTPUT_DIR/file-$i.txt"
    
    # create the file with some content
    echo "This is file $i" > $OUTPUT_DIR/$FILE_NAME
    
    # generate random data and append to the file
    dd if=/dev/urandom of $FILE_NAME bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR