#!/usr/bin/env bash

echo  "== deploy s3 bucket via cfn"

aws cloudformation deploy \
  --template-file s3/iac/cfn/s3-bucket.yaml \
  --stack-name s3-bucket \
  --capabilities CAPABILITY_NAMED_IAM \
  --parameter-overrides \
    BucketName="my-unique-bucket-name" \
    Region="us-west-2" \
    VersioningEnabled=true