#!/usr/bin/env bash

echo  "== deploy s3 bucket via cfn"

STACK_NAME="s3-bucket"

aws cloudformation deploy \
  --template-file s3/iac/cfn/s3-bucket.yaml \
  --stack-name $STACK_namE \
  --Region="us-east-2" \
#   --capabilities CAPABILITY_NAMED_IAM \
#   --parameter-overrides \
#     BucketName="my-unique-bucket-name" \
#     VersioningEnabled=true